# Generated by Django 2.2.15 on 2020-09-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='diameter',
            field=models.CharField(choices=[('10', 'Ten'), ('11', 'Eleven'), ('12', 'Twelve'), ('13', 'Thirteen'), ('14', 'Fourteen'), ('15', 'Fifteen'), ('16', 'Sixteen'), ('17', 'Seventeen'), ('18', 'Eightteen'), ('19', 'Nineteen'), ('20', 'Twenty')], default=0, max_length=2),
        ),
    ]
