# Generated by Django 2.2.15 on 2020-09-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0002_sell_diameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='width',
            field=models.CharField(choices=[('Seven', '7'), ('Seven.5', '7.5'), ('Eight', '8'), ('Eight.5', '8.5'), ('Nine', '9'), ('Nine.5', '9.5'), ('Ten', '10'), ('Ten.5', '10.5'), ('Eleven', '11'), ('Eleven.5', '11.5'), ('Twelve', '12'), ('Twelve.5', '12.5'), ('Thirteen', '13'), ('Thirteen.5', '13.5'), ('Fourteen', '14'), ('Fourteen.5', '14.5'), ('Fifteen', '15')], default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='sell',
            name='diameter',
            field=models.CharField(choices=[('Ten', '10'), ('Eleven', '11'), ('Twelve', '12'), ('Thirteen', '13'), ('Fourteen', '14'), ('Fifteen', '15'), ('Sixteen', '16'), ('Seventeen', '17'), ('Eightteen', '18'), ('Nineteen', '19'), ('Twenty', '20')], default=0, max_length=2),
        ),
    ]
