# Generated by Django 2.2.15 on 2020-09-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0005_auto_20200915_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='bolt_pattern',
            field=models.CharField(choices=[('1', '4x100'), ('2', '4x114.3'), ('3', '5x100'), ('4', '5x114.3')], default=0, max_length=2),
        ),
    ]
