# Generated by Django 2.2.15 on 2020-11-01 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0006_sell_bolt_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='bolt_pattern',
            field=models.CharField(choices=[('4x100', '4x100'), ('4x114.3', '4x114.3'), ('5x100', '5x100'), ('5x114.3', '5x114.3')], default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='sell',
            name='diameter',
            field=models.CharField(choices=[('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='sell',
            name='offset',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='sell',
            name='width',
            field=models.CharField(choices=[('7', '7'), ('7.5', '7.5'), ('8', '8'), ('8.5', '8.5'), ('9', '9'), ('9.5', '9.5'), ('10', '10'), ('10.5', '10.5'), ('11', '11'), ('11.5', '11.5'), ('12', '12'), ('12.5', '12.5'), ('13', '13'), ('13.5', '13.5'), ('14', '14'), ('14.5', '14.5'), ('15', '15')], default=0, max_length=3),
        ),
    ]
